"""
Email summary — sends a report after each scraper run via SMTP.

Required environment variables (set as GitHub Secrets):
  EMAIL_FROM      sender address
  EMAIL_TO        recipient address
  EMAIL_PASSWORD  SMTP password (Gmail app-password or SMTP key)
  EMAIL_SMTP_HOST (optional, default: smtp.gmail.com)
  EMAIL_SMTP_PORT (optional, default: 587)
"""
from __future__ import annotations

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Sequence

from src.core.models import Job


_TEMPLATE = """\
<html><body>
<h2>Job Scraper Run Summary</h2>
<p>Found <strong>{count}</strong> new job listing(s) matching your search.</p>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:sans-serif;font-size:14px;">
  <thead>
    <tr style="background:#f0f0f0;">
      <th>#</th><th>Title</th><th>Company</th><th>Board</th><th>Location</th><th>Link</th>
    </tr>
  </thead>
  <tbody>
    {rows}
  </tbody>
</table>
<br>
<p style="color:#888;font-size:12px;">Generated by job-scraper &mdash; <a href="https://github.com/mtotaro/job-scraper">GitHub</a></p>
</body></html>
"""

_ROW = """\
<tr>
  <td>{n}</td>
  <td>{title}</td>
  <td>{company}</td>
  <td>{board}</td>
  <td>{location}</td>
  <td><a href="{url}">View</a></td>
</tr>
"""


def send_summary(jobs: Sequence[Job], prefix: str = "[JobScraper]") -> None:
    email_from = os.environ.get("EMAIL_FROM", "")
    email_to = os.environ.get("EMAIL_TO", "")
    password = os.environ.get("EMAIL_PASSWORD", "")
    smtp_host = os.environ.get("EMAIL_SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.environ.get("EMAIL_SMTP_PORT", "587"))

    if not all([email_from, email_to, password]):
        print("⚠️  Email credentials not configured — skipping email summary.")
        return

    rows = "".join(
        _ROW.format(n=i + 1, title=j.title, company=j.company, board=j.board,
                    location=j.location, url=j.apply_url)
        for i, j in enumerate(jobs)
    )
    body = _TEMPLATE.format(count=len(jobs), rows=rows if rows else "<tr><td colspan='6'>No new jobs found.</td></tr>")

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"{prefix} {len(jobs)} new job(s) found"
    msg["From"] = email_from
    msg["To"] = email_to
    msg.attach(MIMEText(body, "html"))

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.ehlo()
        server.starttls()
        server.login(email_from, password)
        server.sendmail(email_from, email_to, msg.as_string())

    print(f"✅ Email summary sent to {email_to}")
